version: '2.2'
services:
  mosquitto:
    restart: always
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
    volumes:
      - /${HOME}/docker-data/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /${HOME}/docker-data/mosquitto/data:/mosquitto/data
      - /${HOME}/docker-data/mosquitto/log:/mosquitto/log
