version: "3"

services:
  db:
    container_name: develop1_mariadb
    image: mariadb:10.6
    ports:
      - 13306:3306 # 13306 -> 3306
    volumes:
      - ./mariadb_develop/conf.d:/etc/mysql/conf.d #mysql 인코딩, 기본시간대 설정
      - ./mariadb_develop/data:/var/lib/mysql #DB 데이터가 파일형태로 저장되어 있음
      - ./mariadb_develop/initdb.d:/docker-entrypoint-initdb.d # 컨테이너 최초 실행 시 실행될 스크립트. 주로 테이블 생성과 같은 스크립트가 들어감.
    env_file: ./mariadb_develop/.env #DB 계정정보 설정
    networks:
      - backend
      - default
    restart: always

networks:
  backend:
      name: backend

#link <- external-link *컨테이너간 접근방법* 찾아보기

